### ISSUE TITLE
installation error: it says "Command "python setup.py egg_info" failed with error code 1"

### ISSUE THREAD

**Issue by jagadeesh-vadivel** [vsoch/som#28]
when i try to install som it says: 
>>pip install som
Collecting som
  Using cached https://files.pythonhosted.org/packages/70/89/2a38a0e849dd48cfbd38151e829b9febc293ac8f7ebc756b5cb7508bef86/som-0.2.3.tar.gz
Collecting deid>=0.0.3 (from som)
  Using cached https://files.pythonhosted.org/packages/7e/d0/3d059663ea6eaade66b6bb0c6a488c82a4c5872ce563bf07f0d58836f6ea/deid-0.1.32.tar.gz
Collecting requests>=2.12.4 (from som)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting retrying>=1.3.3 (from som)
  Using cached https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz
Collecting simplejson>=3.10.0 (from som)
  Using cached https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0aff/simplejson-3.16.0.tar.gz
Requirement already satisfied: six>=1.10 in c:\users\jaga1\appdata\local\programs\python\python37\lib\site-packages (from som) (1.12.0)
Collecting pygments>=2.1.3 (from som)
  Using cached https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil in c:\users\jaga1\appdata\local\programs\python\python37\lib\site-packages (from som) (2.7.5)
Collecting urllib3>=1.15 (from som)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting validator.py (from som)
  Using cached https://files.pythonhosted.org/packages/0b/44/0a8c9baa49d5d293a9b174cc5b34cbc615bd277071212de4c95c49088718/validator.py-1.2.5-py2.py3-none-any.whl
Collecting google-api-python-client (from som)
  Using cached https://files.pythonhosted.org/packages/d7/47/940908e52487440f61fb93ad55cbbe3a28235d3bb143b26affb17b37dd28/google_api_python_client-1.7.7-py2.py3-none-any.whl
Collecting google-cloud-datastore (from som)
  Using cached https://files.pythonhosted.org/packages/c9/53/928289d86980d35dfc487f344dc134d2d53fbeddf02514a2e04f43eb7b64/google_cloud_datastore-1.7.3-py2.py3-none-any.whl
Collecting oauth2client==3.0 (from som)
  Using cached https://files.pythonhosted.org/packages/c0/7b/bc893e35d6ca46a72faa4b9eaac25c687ce60e1fbe978993fe2de1b0ff0d/oauth2client-3.0.0.tar.gz
Collecting matplotlib<=2.1.2 (from deid>=0.0.3->som)
  Using cached https://files.pythonhosted.org/packages/6d/bd/3e8cec37bcf71cfd81fe798cf733c046b1ceb123e7dddf6d3435cf03b506/matplotlib-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.1.2]
                    python: yes [3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018,
                            14:57:15) [MSC v.1915 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.15.4]
                       six: yes [using six version 1.12.0]
                  dateutil: yes [using dateutil version 2.7.5]
    backports.functools_lru_cache: yes [Not required]
              subprocess32: yes [Not required]
                      pytz: yes [using pytz version 2018.7]
                    cycler: yes [cycler was not found. pip/easy_install may
                            attempt to install it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [pyparsing was not found. It is required for
                            mathtext support. pip/easy_install may attempt to
                            install it after matplotlib.]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png * Please check http://gnuwin32.sourc
                            * eforge.net/packages/freetype.htm for instructions
                            * to install freetype * Please check http://gnuwin32
                            * .sourceforge.net/packages/libpng.htm for
                            * instructions to install png

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jaga1\AppData\Local\Temp\pip-install-z42fw7kt\matplotlib\

I have already tried "pip3 install som"," pip3 install --upgrade setuptools","pip install --upgrade setuptools" commands it didnt work.

**Comment by vsoch** [comment]
hey @jagadeesh-vadivel ! The package manager pip will install python packages, but not system packages for you. Thankfully, the error message tells us exactly what you are missing:

```
png: no  [The C/C++ header for png (png.h) could not be
                        found.  You may need to install the development
                        package.]
```
and
```
freetype: no  [The C/C++ header for freetype
                        (freetype2\ft2build.h) could not be found.  You may
                        need to install the development package.]
````
Try installing libpng and libfreetype (names may vary depending on your platform) that are needed for building matplotlib. Here is a helpful link for [png.h](https://stackoverflow.com/questions/36674667/png-h-file-not-found-linux) and [freetype](https://github.com/matplotlib/matplotlib/issues/3029). Interestingly, it looks like installing `pkg-config` fixed the error for some users!

If you still have trouble with the above, please share the exact commands you tried and I'll suggest the libraries you need.

**Comment by jagadeesh-vadivel** [comment]
hi @vsoch First of all I am using windows as my platform and tried to install the module som.
From the suggestion i have downloaded the setup files and installed in my machine.
http://gnuwin32.sourceforge.net/packages/freetype.htm
http://gnuwin32.sourceforge.net/packages/libpng.htm
then,
![image](https://user-images.githubusercontent.com/30215636/51426528-16dbbf80-1c12-11e9-97d0-90334b1c76dd.png)

I tried installing freetype-py,pypng,mathplotlib separately it was installed successfully.
But again i get the same error.

what should do now?

**Comment by vsoch** [comment]
If you installed from source they likely aren’t added to your LD_LIBRARY_PATH and they aren’t found. I would do a google search for installing matplotlib on Windows and find instructions that show you how to do this ( I don’t have a Windows machine handy to test for you otherwise I’d try to reproduce!) And likely you will find alternative options to install everything with Conda, which might be desired if the from scratch strategy isn’t working out.

**Comment by jagadeesh-vadivel** [comment]
That would be great help:)
Actually i have already tried conda but in conda SOM package is not available.

**Comment by vsoch** [comment]
Hey @jagadeesh-vadivel there is hope! With anaconda there is usually a pip provided with the installation, for example:

```bash
$ which python
/home/vanessa/anaconda3/bin/python
```
```bash
$ which pip
/home/vanessa/anaconda3/bin/pip
````
This means that you can install dependencies (matplotlib) with conda, then use pip for som and it will be based off of the same shared packages (and thus find matplotlib). Would you care to give that a try?

**Comment by jagadeesh-vadivel** [comment]
Hey @vsoch I tried it but i am not able to run pip command itself.

**Comment by vsoch** [comment]
Could you please show me how you installed anaconda? pip comes with Anaconda, in it's bin. -> https://docs.anaconda.com/anaconda/install/windows/ Note that if you don't add to your PATH, it obviously won't be found.  There might also be a box you need to check according to [this post](https://stackoverflow.com/questions/44231900/i-cant-use-pip-windows). Alternatively, if you create a venv you can always [run the command to install pip](https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment) to see where it gets put. OR you can download [get-pip.py](https://bootstrap.pypa.io/get-pip.py) and run with your installed python as a target to add pip.

**Comment by jagadeesh-vadivel** [comment]
Will try that out. Thanks a lot for responding. Without conda, how could i resolve this issue. because i prefer command prompt.

**Comment by vsoch** [comment]
Without conda, you would need to install the *development* libraries for png and freetype. Since these are for matplotlib, there are a few options [detailed here](https://matplotlib.org/users/installing.html#building-on-windows). As an alternative, if you are familiar with Docker you can run the `continuumio/miniconda3` container and have conda/pip ready to use.

**Comment by jagadeesh-vadivel** [comment]
Will look it into it. @vsoch thanks for responding I ll close thread as of now. And try installing it in conda cvenv.
But the correct procedure to install the development libraries will help a lot.
